<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFrameworks>net8.0;net6.0;netcoreapp3.1</TargetFrameworks>
        <Version>1.0.1</Version>
        <AssemblyVersion>1.0.1</AssemblyVersion>
        <FileVersion>1.0.1</FileVersion>
        <Description>This package contains a lightweight, embeddable C# Zabbix Agent that responds to Zabbix Passive Checks.</Description>
        <RepositoryUrl>https://github.com/nolstoy/nabbix</RepositoryUrl>
        <PackageLicenseUrl>https://github.com/nolstoy/nabbix/blob/master/LICENSE.txt</PackageLicenseUrl>
        <PackageProjectUrl>https://github.com/nolstoy/nabbix</PackageProjectUrl>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Common.Logging" Version="3.4.1" />
        <PackageReference Include="Fasterflect.Netstandard" Version="1.0.8" />
    </ItemGroup>
</Project>
